[workspace]
members = [
 "backfill",
 "discv5",
 "in-memory-state",
 "minimal",
 "oracle",
 "op-bridge", 
 "remote",
 "rollup",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.82"
license = "MIT OR Apache-2.0"
publish = false

[workspace.dependencies]
# reth
reth = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-ethereum = { git = "https://github.com/paradigmxyz/reth", branch = "main", features = ["full"] }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-ethereum-cli = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-discv5 = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-execution-errors = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-execution-types = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-exex = { git = "https://github.com/paradigmxyz/reth", branch = "main", features = ["serde"] }
reth-eth-wire = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-evm = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-network = { git = "https://github.com/paradigmxyz/reth", branch = "main", features = ["test-utils"] }
reth-network-api = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-network-peers = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-node-api = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-revm = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-transaction-pool = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-tracing = { git = "https://github.com/paradigmxyz/reth", branch = "main" }

# alloy
alloy-eips = { version = "0.11", default-features = false }
alloy-genesis = { version = "0.11", default-features = false }
alloy-consensus = { version = "0.11", default-features = false }
alloy-rlp = "0.3.4"
alloy-rpc-types = { version = "0.11", features = [
    "eth",
], default-features = false }
alloy-signer = { version = "0.11", default-features = false }
alloy-signer-local = { version = "0.11", default-features = false }

alloy-primitives = { version = "0.8", default-features = false }
alloy-sol-types  = { version = "0.8", features = ["json"] }

discv5 = "0.8"
enr = "0.12.1"
secp256k1 = { version = "0.29", default-features = false, features = [
 "global-context",
 "recovery",
] }

# async
futures = "0.3"
futures-util = "0.3"
tokio = { version = "1.0", features = ["full"] }
tokio-stream = "0.1"
tokio-tungstenite = { version = "0.24", features = ["native-tls"] }

# serde
serde = "1"
serde_json = "1"

# misc
eyre = "0.6"

# testing
reth-exex-test-utils = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
reth-testing-utils = { git = "https://github.com/paradigmxyz/reth", branch = "main" }
